const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),base=root,read=f=>fs.readFileSync(path.join(base,f),'utf8');
const ctx=vm.createContext({window:{},Date});
vm.runInContext(fs.readFileSync(path.join(root,'data/fleet.generated.js'),'utf8'),ctx);
vm.runInContext(read('web-contracts.generated.js'),ctx);vm.runInContext(read('model.js'),ctx);
const M=ctx.window.CustomerPrototype,fleet=ctx.window.MIQ_MOCK_DATA.fleet,owner={role:'customer_owner'};
const rows=M.buildVehicles(fleet),items=M.serviceRecords(rows,{kind:'supplies'}),initial=JSON.stringify(rows);
for(const role of ['customer_staff','internal','dealer_owner',''])assert.equal(M.resetSupplies(rows,{role},[items[0].id]).length,0);
assert.equal(M.resetSupplies(rows,owner,[]).length,0);
assert.equal(M.resetSupplies(rows,owner,[items[0].id,'unknown']).length,0,'Invalid batch must be atomic');
assert.equal(M.resetSupplies(rows,{...owner,group:'out-of-scope'},[items[0].id]).length,0);
assert.equal(JSON.stringify(rows),initial);
const done=M.resetSupplies(rows,owner,[items[0].id,items[0].id]);assert.equal(done.length,1,'Deduplicate selected items');
assert.equal(M.supplyItems(rows[0])[0].usedHours,0);assert.equal(M.supplyItems(rows[0])[0].key,'normal');
assert.equal(M.supplyItems(rows[0])[0].lastChangedAt,M.SNAPSHOT);assert.equal(rows[0].supplyDueCount,1);assert.equal(rows[0].supplySoonCount,1);
assert.equal(M.resetSupplies(rows,owner,[items[0].id]).length,0,'Do not reset already-zero items');
assert.equal(M.undoSupplyReset(rows,{role:'customer_staff'},done),false);assert.equal(M.undoSupplyReset(rows,owner,done),true);
assert.equal(JSON.stringify(rows),initial,'Undo restores counts and replacement dates');
const harness=vm.runInNewContext('('+fs.readFileSync(path.join(__dirname,'harness.js'),'utf8')+')',{vm,URL,URLSearchParams,M,fleet,read});
const h=harness('#services?service=supplies&role=customer_owner');
const select=(h,id,on=true)=>h.listeners.change({target:{dataset:{supplySelect:id},checked:on}});
const all=(h,on=true)=>h.listeners.change({target:{dataset:{},checked:on,hasAttribute:k=>k==='data-supply-select-all'}});
assert(h.html().includes('data-open-supply-reset'));
select(h,items[0].id);assert.equal(h.node('#supply-selection-count').textContent,'1개 선택');assert(h.node('[data-supply-select-all]').indeterminate);
h.click({},'data-open-supply-reset');assert(h.node('#supply-reset-dialog').open);assert(h.node('#supply-reset-items').innerHTML.includes(items[0].name));
h.click({},'data-close-supply-reset');assert(!h.node('#supply-reset-dialog').open);assert(h.html().includes('231%'),'Cancel does not reset');
h.click({},'data-confirm-supply-reset');assert(h.html().includes('231%'),'Closed dialog cannot execute');
h.click({},'data-open-supply-reset');h.click({},'data-confirm-supply-reset');assert(!h.html().includes('사용 0 h / 주기 100 h'),'Web service list excludes normal supplies');assert(h.html().includes('교체 필요 2개'));
h.click({},'data-undo-supply-reset');assert(h.html().includes('231%'));assert(h.html().includes('교체 필요 3개'));
all(h);assert.equal(h.node('#supply-selection-count').textContent,items.length+'개 선택');
all(h,false);assert(h.node('[data-open-supply-reset]').disabled);
select(h,items[0].id);h.open('services?service=supplies&group=테스트그룹');assert.equal(h.node('#supply-selection-count').textContent,'0개 선택');
h.open('services?service=supplies&role=customer_owner');select(h,items[0].id);h.click({},'data-open-supply-reset');h.open('settings?role=customer_staff');assert(!h.node('#supply-reset-dialog').open);
h.click({},'data-confirm-supply-reset');h.open('services?service=supplies&role=customer_owner');assert(h.html().includes('231%'));
for(const role of ['customer_staff'])for(const view of ['services?service=supplies','supplies?equipmentId='+rows[0].equipmentId]){
  const staff=harness('#'+view+'&role='+role);assert(!staff.html().includes('data-open-supply-reset'));assert(!staff.html().includes('data-supply-select'));
  select(staff,items[0].id);staff.click({},'data-open-supply-reset');assert(!staff.node('#supply-reset-dialog').open);
}
const single=harness('#supplies?equipmentId='+rows[0].equipmentId+'&role=customer_owner');all(single);assert.equal(single.node('#supply-selection-count').textContent,'3개 선택');
single.click({},'data-open-supply-reset');single.click({},'data-confirm-supply-reset');assert(single.html().includes('사용 0 h / 주기 100 h'));assert(single.html().includes('사용 0 h / 주기 250 h'));
single.open('home');assert(single.html().includes('금일 현황'));single.open('detail?equipmentId='+rows[0].equipmentId);assert(single.html().includes('data-supply-state="normal"'));
for(const f of ['model.js','customer.js'])new vm.Script(read(f));
console.log('PASS: owner-only selection/reset/undo; atomic scope validation; cancel, stale dialog, group/role changes; summary counts and detail state.');
